### ISSUE TITLE
No compatibility with secrets

### ISSUE THREAD

**Issue by backmind** [hotio/cloudflareddns#20]
Hey guys,

is there any way you update the image to get working with secrets? I wish to isolate CF tokens from env file :)

Best,

**Comment by backmind** [comment]
Setting up my docker-compose, I can not load "_FILE" to force load secrets from fliles defined earlier. Am I doing it wrong?

Example:

````
  cf-ddns:
    container_name: cf-ddns
    image: cr.hotio.dev/hotio/cloudflareddns
    environment:
     ...
      - CF_USER_FILE=/run/secrets/cf_email
      - CF_APIKEY_FILE=/run/secrets/cf_api_key
      - CF_APITOKEN_ZONE_FILE=/run/secrets/cf_token_zone
     ...
    networks:
      - socket_proxy
    volumes:
      - $DOCKERDIR/hotio_cloudflare:/config
    secrets:
      - cf_email
      - cf_api_key
      - cf_token_zone
```

where secrets are:

```
secrets:
  cf_email:
    file: $SECRETSDIR/CLOUDFLARE_EMAIL.txt
  cf_api_key:
    file: $SECRETSDIR/CLOUDFLARE_API_KEY.txt
  cf_token_zone:
    file: $SECRETSDIR/CLOUDFLARE_APITOKEN_ZONE.txt
```
